version: '3'

# Copy this file as "docker-compose.override.yml", and use it to override/add configuration on your containers.
# You can find a detailed documentation here: https://docs.akeneo.com/master/install_pim/docker/installation_docker.html

services:
  fpm:
    environment:
      COMPOSER_HOME: '/home/docker/.composer'
      PHP_IDE_CONFIG: 'serverName=pim-ce-cli'
      PHP_XDEBUG_ENABLED: "${PHP_XDEBUG_ENABLED:-0}"
      XDEBUG_CONFIG: 'remote_host=172.17.0.1'
  
  httpd:
    environment:
      PHP_IDE_CONFIG: 'serverName=pim-ce'

  mysql:
    ports:
      - '33006:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'

  elasticsearch:
    ports:
      - '9210:9200'
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'

volumes:
  mysqldata:
    driver: local
  esdata:
    driver: local
